export const data = [
  {
    id: 1,
    card: "/create-card/tablecard-ls.svg",
    xpert: "Abdulraheem Yusuf",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Active",

  },
  {
    id: 2,
    card: "/create-card/tablecard-ls.svg",
    xpert: "Abisoye Lukmanf",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Active",

  },
  {
    id: 3,
    card: "/create-card/tablecard-ls.svg",
    xpert: "Abraham Adekunle",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",

  },
  {
    id: 4,
    card: "/create-card/tablecard-ls.svg",
    xpert: "Abraham Adekunle",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",
  },
  {
    id: 5,
    card: "/create-card/tablecard-pt.svg",
    xpert: "Abdulraheem Yusuf",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",
    width: 13.71,
    height: 24

  },
   { id: 6,
    card: "/create-card/tablecard-pt.svg",
    xpert: "Ayodeji Balogun",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",
    width: 13.71,
    height: 24
  },
   { id: 7,
    card: "/create-card/tablecard-pt.svg",
    xpert: "Ayodeji Balogun",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",
    width: 13.71,
    height: 24
  },
   { id: 8,
    card: "/create-card/tablecard-ls.svg",
    xpert: "Babatunde Adekunle",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",
  },
   { id: 9,
    card: "/create-card/tablecard-pt.svg",
    xpert: "Cynthia Chia",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",
    width: 13.71,
    height: 24
  },
   { id: 10,
    card: "/create-card/tablecard-ls.svg",
    xpert: "Ekene Smart",
    email: "ayusuf@afexnigeria.com",
    designation: "VP, Innovation and Technology",
    status: "Inactive",
  },
];
